rootpy/rootpy

examples/plotting/plot_matplotlib_hist2d.py

```python
plot_matplotlib_hist2d.py:21: RuntimeWarning: covariance is not positive-semidefinite.
```

[MRG] fix plot_matplotlib_hist2d.py covariance matrix

---

rootpy/__init__.py

Not that one should ever do this...

[MRG] Fix from rootpy import *

---

rootpy/plotting/root2matplotlib.py

Also fixes the potential use case of ```emptybins=False``` and ```yerr=None```

Bug fix for issue #638

---

README.rst
docs/index.rst

http://dx.doi.org/10.5281/zenodo.18897

add DOI badge

---

.travis.yml

ROOT 5.34.18 -> 5.34.34

---

rootpy/tree/tests/test_tree.py
rootpy/tree/tree.py

tree.Draw: accept list expression to avoid regex problem with ternary expressions

---

rootpy/info.py
rootpy/io/file.py
rootpy/root2hdf5.py
rootpy/tests/test_root2hdf5.py

fix deprecation warnings and fix #684

---

README.rst
docs/index.rst

https://bitbucket.org/pypa/pypi/issues/396/download-stats-have-stopped-working-again

remove download stats since they are broken again on pypi

---

rootpy/io/pickler.py
rootpy/io/tests/test_pickler.py

xref #692 
Also add a unit test to check that proxy reads are delayed.

FIX #692: Proxy read broken in rootpy.io.pickler.load

---

.travis.yml

set CONDA_ENV_PATH

---

rootpy/compiled.py

remove use of check_output to restore py2.6 compat

---

rootpy/plotting/hist.py

fix #659: Hist.divide now accepts THStack/HistStack

---

rootpy/plotting/hist.py
rootpy/plotting/tests/test_hist.py
rootpy/roosh.py
rootpy/tests/test_root2hdf5.py

Fix #713: Hist.merge_bins was broken when supplying multiple bin ranges

---

Makefile
rootpy/ROOT.py
rootpy/__init__.py
rootpy/tree/categories.py
rootpy/utils/quickroot.py

Force the same class method to be called even when subclassing.

tree.Categories: use Categories instead of cls in from_string

---

rootpy/__init__.py
rootpy/stats/plottable.py
rootpy/stats/tests/test_plottable.py

Cherry-pick #599: classes for RooPlot, RooCurve and RooHist

---

rootpy/__init__.py
rootpy/plotting/base.py
rootpy/plotting/hist.py
rootpy/plotting/tests/test_plottable.py
rootpy/tests/test_base.py

fix #668: asrootpy not preserving plottable attributes

---

rootpy/plotting/graph.py
rootpy/plotting/tests/test_graph.py

fix Graph operators: use new GraphPoint instead of indexing

---

rootpy/ROOT.py
rootpy/plotting/__init__.py
rootpy/plotting/base.py
rootpy/plotting/legend.py
rootpy/tree/tree.py

Yikes, many changes in 6.9.2... Still not full support yet.

changes for ROOT 6.9.2

---

rootpy/plotting/utils.py

If axes are unspecified, use first plottable

---

docs/modules/trees.rst
rootpy/tree/texttree.py
rootpy/tree/tree.py

This is the texttree addition listed in #737. It uses `.b` to access the branches. Added mention in docs.
```python
In [1]: from rootpy import io
In [2]: tups = io.File('tuples.root')
In [3]: hlt2 = tups.TupleHlt2
In [4]: hlt2.b.FullEventSize
Out[4]: 'FullEventSize'
In [5]: hlt2.b.FullEventSize > 1
Out[5]: '(FullEventSize>(1))'
In [6]: type(_)
Out[6]: rootpy.tree.cut.Cut
In [8]: hlt2.b.
hlt2.b.FullEventSize                   
hlt2.b.FullRB46                        
hlt2.b.FullRB87                        
hlt2.b.FullRB88                        
hlt2.b.FullRB90                        
hlt2.b.Hlt2B2HH_B2HH
```

Adding texttree

---

rootpy/info.py
rootpy/plotting/hist.py

fix #762 and bump to 0.9.2

---

rootpy/plotting/style/__init__.py
rootpy/tree/filtering.py

py3: iteritems -> items

---

rootpy/plotting/func.py

Changes to be committed:
modified:   rootpy/plotting/func.py

FIX Issue #783 python3 vs python2 string and a typo issue #784 in func.py

---

rootpy/plotting/graph.py

Fix a bug in error_low.setter
